services:
  warriors-pr3-db:
    image: postgres:15
    container_name: warriors-pr3-postgres
    environment:
      POSTGRES_USER: "warrior"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "warriors_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "8432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warrior -d warriors_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - webnet

volumes:
  pg_data:

networks:
  webnet:
    driver: bridge
